### ISSUE TITLE
No GPU acceleration

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-up-board#26] opened 2017-08-05 10:02 UTC
The latest `2.2.0+rev1` does not seem to have GPU acceleration. As tested by @curcuz, every GPU flag is disabled and no HW acceleration is detected by chromium.

**Comment by imrehg** [comment] 2017-08-05 10:04
Sorry, should be filed at https://github.com/resin-os/resinos/issues/370 I guess...

**Comment by imrehg** [comment] 2017-08-11 18:00
Refiled here as requested.

**Comment by curcuz** [comment] 2017-08-16 18:44
from the investigation @telphan performed, it turns out the issue is with the mesa libraries that are installed by `debian:jessie`. The way to fix this is to update these packages.
To do that add the jessie-backports mirror to your source.list file, by adding the following line to your Dockerfile:
`RUN echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list`
Lastly use apt-get with `-t jessie-backports` flag to install from that source:
`apt-get -t jessie-backports install {packages}`

**Comment by floion** [comment] 2017-08-17 05:36
@curcuz maybe we can have this directly in the base images?

**Comment by floion** [comment] 2017-08-17 10:19
cc @nghiant2710 ^

**Comment by floion** [comment] 2017-08-31 13:41
@telphan can this be closed now? What is the current resolution?

**Comment by nghiant2710** [comment] 2017-09-07 08:46
@curcuz @telphan can you please test this again using `debian:stretch` as the base images which has a newer stable mesa library

**Comment by floion** [comment] 2017-09-28 11:43
ping @telphan ^

**Comment by floion** [comment] 2017-11-08 08:47
ping @telphan

**Comment by telphan** [comment] 2017-11-10 13:46
@nghiant2710 will do

**Comment by floion** [comment] 2018-01-15 13:27
ping @telphan

**Comment by floion** [comment] 2018-01-29 08:59
ping @telphan

**Comment by floion** [comment] 2018-02-02 19:12
ping @telphan

**Comment by telphan** [comment] 2018-03-05 15:19
@nghiant2710 yes, `debian:stretch` should do the trick here.

EDIT: also tested

**Comment by floion** [comment] 2018-03-27 05:18
So @telphan can this be closed? Did you test it with debian:stretch and confirm the issue is no longer present?

**Comment by telphan** [comment] 2018-06-17 15:00
This was tested on debian:stretch. Closing the ticket as this is fixed.

**Closed by telphan** 2018-06-17 15:00 UTC
